### ISSUE TITLE
[Bug Report] maximum device name length is 64 characters

### ISSUE THREAD

**Issue by jochumdev** [bketelsen/incus-compose#121]
**Describe the bug**

INFO  Creating BindMount name=home-jochumdev-cache-octocompose-opencloud01-template-32db6de97cc44b0b29392eb0caeff068-yaml
ERROR Start error="Invalid devices: The maximum device name length is 64 characters"

**To Reproduce**

```yaml
name: opencloud01
services:
  opencloud:
    command:
      - -c
      - opencloud init || true; opencloud server
    entrypoint:
      - /bin/sh
    environment:
      COLLABORA_DOMAIN: collabora.example.org
      COMPANION_DOMAIN: companion.example.org
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142
      IDM_ADMIN_PASSWORD: notSecure
      IDM_CREATE_DEMO_USERS: "false"
      MICRO_REGISTRY_ADDRESS: 127.0.0.1:9233
      NATS_NATS_HOST: 0.0.0.0
      NATS_NATS_PORT: "9233"
      NOTIFICATIONS_SMTP_HOST: mail.example.org
      NOTIFICATIONS_SMTP_INSECURE: "false"
      NOTIFICATIONS_SMTP_PORT: "587"
      NOTIFICATIONS_SMTP_SENDER: OpenCloud notifications <cloud@example.org>
      NOTIFICATIONS_SMTP_USERNAME: cloud@example.org
      OC_ADD_RUN_SERVICES: notifications
      OC_INSECURE: "false"
      OC_LOG_COLOR: "false"
      OC_LOG_LEVEL: info
      OC_LOG_PRETTY: "false"
      OC_PASSWORD_POLICY_BANNED_PASSWORDS_LIST: banned-password-list.txt
      OC_URL: https://cloud.example.org
      ONLYOFFICE_DOMAIN: onlyoffice.example.org
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/opencloud/csp.yaml
      PROXY_ENABLE_BASIC_AUTH: "false"
      PROXY_TLS: "false"
    image: docker:opencloudeu/opencloud-rolling:2.0.0
    labels:
      traefik.enable: "true"
      traefik.http.routers.opencloud.entrypoints: https
      traefik.http.routers.opencloud.rule: Host(`cloud.example.org`)
      traefik.http.routers.opencloud.service: opencloud
      traefik.http.routers.opencloud.tls.certresolver: http
      traefik.http.services.opencloud.loadbalancer.server.port: "9200"
    logging:
      driver: local
    networks:
      opencloud-net: null
    restart: always
    volumes:
      - type: bind
        source: /home/jochumdev/.cache/octocompose/opencloud01/files/91d2230b17ccbc6774b57f6efc840314.yaml
        target: /etc/opencloud/app-registry.yaml
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /home/jochumdev/.cache/octocompose/opencloud01/template/32db6de97cc44b0b29392eb0caeff068.yaml
        target: /etc/opencloud/csp.yaml
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /home/jochumdev/.cache/octocompose/opencloud01/files/ec8a8eb48a47e77e6d413d10e23e8a32.txt
        target: /etc/opencloud/banned-password-list.txt
        read_only: true
        bind:
          create_host_path: true
      - type: volume
        source: opencloud-config
        target: /etc/opencloud
        volume: {}
      - type: volume
        source: opencloud-data
        target: /var/lib/opencloud
        volume: {}
      - type: volume
        source: opencloud-apps
        target: /var/lib/opencloud/web/assets/apps
        volume: {}
  traefik:
    command:
      - --log.level=ERROR
      - --certificatesResolvers.http.acme.email={{.configs.traefik.acme.email}}
      - --certificatesResolvers.http.acme.storage=/certs/acme.json
      - --certificatesResolvers.http.acme.httpChallenge.entryPoint=http
      - --certificatesResolvers.http.acme.caserver={{.configs.traefik.acme.caserver}}
      - --api.dashboard={{.configs.traefik.dashboard}}
      - --entryPoints.http.address=:80
      - --entryPoints.http.http.redirections.entryPoint.to=https
      - --entryPoints.http.http.redirections.entryPoint.scheme=https
      - --entryPoints.https.address=:443
      - --entryPoints.https.transport.respondingTimeouts.readTimeout=12h
      - --entryPoints.https.transport.respondingTimeouts.writeTimeout=12h
      - --entryPoints.https.transport.respondingTimeouts.idleTimeout=3m
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedByDefault=false
      - --accessLog=true
      - --accessLog.format=json
      - --accessLog.fields.headers.names.X-Request-Id=keep
    image: docker:library/traefik:v3.3.4
    labels:
      traefik.enable: "false"
      traefik.http.middlewares.traefik-auth.basicauth.users: admin:$$apr1$$4vqie50r$$YQAmQdtmz5n9rEALhxJ4l.
      traefik.http.routers.traefik.entrypoints: https
      traefik.http.routers.traefik.middlewares: traefik-auth
      traefik.http.routers.traefik.rule: Host(`traefik.opencloud.test`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.tls.certresolver: http
    logging:
      driver: local
    networks:
      opencloud-net:
        aliases:
          - cloud.example.org
          - collabora.example.org
          - onlyoffice.example.org
          - wopiserver.example.org
          - companion.example.org
    ports:
      - mode: ingress
        target: 80
        published: "80"
        protocol: tcp
      - mode: ingress
        target: 443
        published: "443"
        protocol: tcp
      - mode: ingress
        target: 443
        published: "443"
        protocol: udp
    restart: always
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
        bind:
          create_host_path: true
      - type: volume
        source: certs
        target: /certs
        volume: {}
networks:
  opencloud-net:
    name: opencloud01_opencloud-net
volumes:
  certs:
    name: opencloud01_certs
  opencloud-apps:
    name: opencloud01_opencloud-apps
  opencloud-config:
    name: opencloud01_opencloud-config
  opencloud-data:
    name: opencloud01_opencloud-data
```

run this yaml with `incus-compose up`

**Expected behavior**

runs with mounts.

**Compose File**

**Incus Version**

main branch
