### ISSUE TITLE
No way to add existing storage volume

### ISSUE THREAD

**Issue by janm84** [bketelsen/incus-compose#87]
Hello there,

at the moment it seems, that there is no way to add existing storage volumes like:

```
    - type: disk
       source: default_frigate_storage
       target: /media/frigate
       x-incus-shift: true

volumes:
  frigate_storage:
    driver: incus
    driver_opts:
      pool: storage_ext
```

In some cases it would be useful to add volumes with needed data.

Lokking forward to your feedback

BR, Jan
